sudo: required

language: go

go:
  - 1.9.x
install:
  - echo "Please don't go get"
  
services:
  - docker

before_script:
  - curl -sSL test.docker.com | sudo -E sh

script:
  - cd queue-worker && ./build.sh

after_success:
    - if [ ! -z "$TRAVIS_TAG" ] ; then
    
        if [ -z $DOCKER_NS ] ; then
          export DOCKER_NS=functions;
          fi

        docker tag $DOCKER_NS/queue-worker:latest-dev $DOCKER_NS/queue-worker:$TRAVIS_TAG;
        echo $DOCKER_PASSWORD | docker login -u=$DOCKER_USERNAME --password-stdin;
        docker push $DOCKER_NS/queue-worker:$TRAVIS_TAG;
        fi